//! Unit tests for document emission.

use crate::diagnostics::Diagnostics;
use crate::ir::{Block, Document, Inline, MathSource};
use crate::metadata::Metadata;
use crate::typst::{emit_document, RenderOptions};

fn text(value: &str) -> Inline {
    Inline::text(value)
}

fn emit(document: &Document) -> String {
    let mut diagnostics = Diagnostics::new();
    emit_document(
        document,
        &RenderOptions::document_default(),
        &mut diagnostics,
    )
    .unwrap_or_else(|error| panic!("emission failed: {error}"))
}

/// The `#show:` call from generated output, which is where metadata appears.
///
/// The inlined template also mentions every field name, as parameter defaults,
/// so an assertion about which arguments were passed has to look here.
fn show_rule(output: &str) -> &str {
    // Searched from the end: the inlined template's own documentation mentions
    // `#show: article.with(...)`, and the generated rule is always last.
    let start = output.rfind("\n#show: article").expect("a show rule") + 1;
    let rest = &output[start..];
    let end = rest.find("\n\n").unwrap_or(rest.len());
    rest[..end].trim_end()
}

fn metadata() -> Metadata {
    Metadata {
        title: Some("Peer Effects".into()),
        subtitle: Some("Strategic Complementarities".into()),
        author: Some("Jane Researcher".into()),
        date: Some("October 2026".into()),
        ..Metadata::default()
    }
}

fn sample() -> Document {
    Document::new(
        metadata(),
        vec![
            Block::heading(1, vec![text("Regression")]),
            Block::Paragraph(vec![text("Consider the linear model")]),
            Block::Math(MathSource::display(r"Y_i = X_i^\top \beta + \varepsilon_i")),
        ],
    )
}

#[test]
fn the_generated_file_is_self_contained() {
    let output = emit(&sample());

    // The template is inlined rather than imported, so the output compiles on
    // its own and can be inspected or edited.
    assert!(output.contains("#let article("), "{output}");
    assert!(!output.contains("#import"), "{output}");
}

#[test]
fn the_generated_file_says_it_is_generated() {
    assert!(emit(&sample()).starts_with("// Generated by maddy."));
}

#[test]
fn the_template_is_applied_with_a_show_rule_carrying_the_metadata() {
    let rule = show_rule(&emit(&sample())).to_string();

    assert!(rule.starts_with("#show: article.with("), "{rule}");
    assert!(rule.contains(r#"title: "Peer Effects""#), "{rule}");
    assert!(
        rule.contains(r#"subtitle: "Strategic Complementarities""#),
        "{rule}"
    );
    assert!(rule.contains(r#"author: "Jane Researcher""#), "{rule}");
    assert!(rule.contains(r#"date: "October 2026""#), "{rule}");
}

#[test]
fn absent_metadata_fields_are_omitted_rather_than_blank() {
    // A template must be able to tell "no title" from "empty title", so that it
    // can decide whether to render a title block at all.
    let document = Document::new(
        Metadata {
            title: Some("Only a title".into()),
            ..Metadata::default()
        },
        vec![],
    );
    let rule = show_rule(&emit(&document)).to_string();

    assert!(rule.contains(r#"title: "Only a title""#), "{rule}");
    assert!(!rule.contains("subtitle:"), "{rule}");
    assert!(!rule.contains("author:"), "{rule}");
    assert!(!rule.contains("date:"), "{rule}");
}

#[test]
fn a_document_with_no_metadata_applies_the_template_without_arguments() {
    let document = Document::new(Metadata::default(), vec![Block::Rule]);
    assert_eq!(show_rule(&emit(&document)), "#show: article");
}

#[test]
fn metadata_values_are_escaped_as_string_literals() {
    let document = Document::new(
        Metadata {
            title: Some(r#"A "quoted" \ title"#.into()),
            ..Metadata::default()
        },
        vec![],
    );
    assert!(show_rule(&emit(&document)).contains(r#"title: "A \"quoted\" \\ title""#));
}

#[test]
fn the_body_follows_the_show_rule() {
    let output = emit(&sample());
    let show = output.rfind("\n#show: article").expect("a show rule");
    let body = output.find("= Regression").expect("the body");
    assert!(show < body, "{output}");
}

#[test]
fn the_generated_source_is_not_minified() {
    // Readable output is a stated goal: it is how a renderer bug gets diagnosed.
    let output = emit(&sample());
    assert!(
        output.contains("= Regression\n\nConsider the linear model\n\n$ "),
        "{output}"
    );
}

#[test]
fn an_empty_document_still_emits_a_valid_file() {
    let output = emit(&Document::default());
    assert!(output.contains("#let article("));
    assert!(output.trim_end().ends_with("#show: article"), "{output}");
}

#[test]
fn a_math_failure_propagates_out_of_emission() {
    let document = Document::new(
        Metadata::default(),
        vec![Block::Math(MathSource::display(r"\foo"))],
    );
    let mut diagnostics = Diagnostics::new();
    let result = emit_document(
        &document,
        &RenderOptions::document_default(),
        &mut diagnostics,
    );
    assert!(result.is_err());
}

// ----------------------------------------------- verified against real Typst

#[test]
fn the_generated_document_compiles_under_typst() {
    let document = Document::new(
        metadata(),
        vec![
            Block::heading(1, vec![text("Regression")]),
            Block::Paragraph(vec![
                text("Consider "),
                Inline::Strong(vec![text("the")]),
                text(" model with "),
                Inline::Math(MathSource::inline(r"X_i \in \mathbb R^K")),
                text(", costs #5, and a - dash."),
            ]),
            Block::Math(MathSource::display(
                r"\hat\beta = \left(\sum_{i=1}^{n} X_i X_i^\top\right)^{-1}\sum_{i=1}^{n} X_i Y_i",
            )),
            Block::UnorderedList(vec![
                crate::ir::ListItem::text(vec![text("first")]),
                crate::ir::ListItem::new(vec![
                    Block::Paragraph(vec![text("second")]),
                    Block::UnorderedList(vec![crate::ir::ListItem::text(vec![text("nested")])]),
                ]),
            ]),
            Block::OrderedList {
                start: 3,
                items: vec![crate::ir::ListItem::text(vec![text("third")])],
            },
            Block::Table(crate::ir::Table {
                alignments: vec![crate::ir::Alignment::None, crate::ir::Alignment::Right],
                header: vec![vec![text("Model")], vec![text("Estimate")]],
                rows: vec![vec![vec![text("OLS")], vec![text("0.42")]]],
            }),
            Block::CodeBlock(crate::ir::CodeBlock {
                language: Some("rust,ignore".into()),
                source: "fn main() { let s = \"`\"; }\n".into(),
            }),
            Block::BlockQuote(vec![Block::Paragraph(vec![text(
                "Models are abstractions.",
            )])]),
            Block::Rule,
            Block::Paragraph(vec![text("- a line that must not become a list")]),
        ],
    );

    let output = emit(&document);
    let Some(text) = crate::typst::tests::render_text(&output) else {
        return; // Typst is unavailable; the assertions above still hold.
    };

    // Compilation succeeded, and the content survived.
    assert!(text.contains("Regression"), "{text}");
    assert!(text.contains("costs #5"), "{text}");
    assert!(
        text.contains("- a line that must not become a list"),
        "{text}"
    );
}
