//! Document emission.
//!
//! The generated file is self-contained: the chosen template is inlined, then
//! applied with a show rule, then the body follows. That makes `--emit typst`
//! and `--keep-typst` genuinely useful — the output can be compiled, read and
//! edited on its own.

use crate::diagnostics::{Diagnostics, Result};
use crate::ir::Document;
use crate::metadata::Metadata;

use super::escape;
use super::markup::Renderer;
use super::RenderOptions;

/// Render a document as Typst source.
pub fn emit_document(
    document: &Document,
    options: &RenderOptions,
    diagnostics: &mut Diagnostics,
) -> Result<String> {
    let body = Renderer::new(diagnostics).blocks(&document.blocks)?;

    let mut out = String::from("// Generated by maddy. Edits will be overwritten.\n\n");
    out.push_str(options.template.trim_end());
    out.push_str("\n\n");
    out.push_str(&show_rule("article", &document.metadata));
    out.push_str("\n\n");
    out.push_str(&body);
    out.push('\n');

    Ok(out)
}

/// The show rule that applies a template, carrying the document's metadata.
///
/// Fields the document did not supply are omitted rather than passed as empty
/// strings, so a template can distinguish "absent" from "blank" and decide, for
/// instance, whether to render a title block at all.
pub(super) fn show_rule(function: &str, metadata: &Metadata) -> String {
    let arguments = template_arguments(metadata);
    if arguments.is_empty() {
        return format!("#show: {function}");
    }
    format!("#show: {function}.with(\n  {},\n)", arguments.join(",\n  "))
}

/// The metadata arguments a template receives.
pub(super) fn template_arguments(metadata: &Metadata) -> Vec<String> {
    [
        ("title", &metadata.title),
        ("subtitle", &metadata.subtitle),
        ("author", &metadata.author),
        ("date", &metadata.date),
    ]
    .into_iter()
    .filter_map(|(name, value)| {
        let value = value.as_deref()?;
        Some(format!("{name}: {}", escape::string_literal(value)))
    })
    .collect()
}
