//! Presentation emission.
//!
//! The shape mirrors document emission — inline the template, apply it, then the
//! content — but the content is a sequence of `slide` calls rather than a flat
//! body, and a title slide is generated when the metadata asks for one.

use crate::diagnostics::{Diagnostics, Result};
use crate::ir::{Presentation, Slide};

use super::document::{prelude, show_rule, template_arguments};
use super::markup::Renderer;
use super::RenderOptions;

/// Render a presentation as Typst source.
pub fn emit_presentation(
    presentation: &Presentation,
    options: &RenderOptions,
    diagnostics: &mut Diagnostics,
) -> Result<String> {
    let mut out = String::from("// Generated by maddy. Edits will be overwritten.\n\n");
    out.push_str(options.template.trim_end());
    out.push_str("\n\n");
    out.push_str(&show_rule("presentation", &presentation.metadata));
    out.push_str("\n\n");
    out.push_str(&prelude(options));

    // A title triggers the title slide; the other fields merely fill it in.
    if presentation.has_title_slide() {
        let arguments = template_arguments(&presentation.metadata);
        out.push_str(&format!(
            "#title-slide(\n  {},\n)\n\n",
            arguments.join(",\n  ")
        ));
    }

    for slide in &presentation.slides {
        out.push_str(&emit_slide(slide, diagnostics)?);
        out.push_str("\n\n");
    }

    Ok(out)
}

/// Render one slide as a call to the theme's `slide` function.
fn emit_slide(slide: &Slide, diagnostics: &mut Diagnostics) -> Result<String> {
    let mut renderer = Renderer::new(diagnostics);

    // The title is content, not a string, so that inline markup and mathematics
    // work in a slide title.
    let title = match &slide.title {
        Some(content) => Some(renderer.inlines(content, false)?),
        None => None,
    };

    let body = renderer.blocks(&slide.blocks)?;
    let body = indent(&body, 2);

    Ok(match title {
        Some(title) => format!("#slide(title: [{title}])[\n{body}\n]"),
        None => format!("#slide[\n{body}\n]"),
    })
}

/// Indent every non-empty line, so the generated source stays readable.
fn indent(text: &str, spaces: usize) -> String {
    let pad = " ".repeat(spaces);
    text.lines()
        .map(|line| {
            if line.trim().is_empty() {
                String::new()
            } else {
                format!("{pad}{line}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}
